### PR TITLE
modify install_requirements.py to work with pip3

### PR DESCRIPTION
**Pull request by dimitrios-ath**
In order to resolve issue #237, I modified "install_requirements.py" to work with pip and pip3 before failing.

### CODE REVIEW

**Comment by dimitrios-ath** [comment]
I'm sorry for the formatting issue, now I think it will be fine. Thanks!

**Comment by dimitrios-ath** [comment]
Now that all tests completed successfully, is it ready for a review? Should I manually assign someone to review?

**Comment by nickjalbert** [comment]
Looks great!  Thanks @dimitrios-ath :)

**Comment by andyk** [comment]
Yeah great work! Are you interested in working on anything else in AgentOS? We are going to be cutting the 0.1.0 release in the next month, which will be large evolution of the project architecture from the 0.7.0 release that is almost a year old. It would be super awesome to see more contributions from you!

**Comment by dimitrios-ath** [comment]
I am currently very busy due to university exams, but this seems a very interesting project. Maybe in the future I will try to contribute more! Thanks again for the fast responses and the overall support! :)

**Pull request merged**
