### PR TITLE
Add example A2C and PPO agents from Ilya's repo

### PR DESCRIPTION
**Pull request by nickjalbert**
This PR adds an example agent from Ilya's [PyTorch A2C, PPO, ACKTR, and GAIL repo](https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail) (which I've been abbreviating as PAPAG).  I basically ported over the `main.py` from his repo and AgentOS'd it (i.e. made it play nice with our model saving/loading system and track training stats).

Currently it runs against environment `PongNoFramskip-v4` (this env is **not** broken out into its own component yet) and you can choose between A2C and PPO algos by passing a specific argument set.  There's an argument set for ACKTR as well, but that doesn't converge on my CPU.  

To demo:

```bash
# Train A2C
agentos run agent --entry-point learn --arg-set-file a2c_pong_args.yaml
# Evaluate A2C
agentos run agent --entry-point evaluate --arg-set-file a2c_pong_args.yaml

# Train PPO
agentos run agent --entry-point learn --arg-set-file ppo_pong_args.yaml
# Evaluate PPO
agentos run agent --entry-point evaluate --arg-set-file ppo_pong_args.yaml
```

I also went through and upgraded PyTorch in the reqs for the agents that need it.  I'm not sure the upgrade is strictly necessary, so maybe you could try creating a new environment on your M1 and see if this upgrade breaks everything 😬  (if so, I'll try to back out the upgrade and see if everything still works).

### CODE REVIEW

**Comment by nickjalbert** [comment]
It looks like the certificate for the pytorch extra index site expired, breaking the install of the CPU-only torch on linux. :/

Hopefully they will fix soon...

**Comment by nickjalbert** [comment]
@andyk this is ready for a review!

**Comment by andyk** [comment]
I got your branch working locally and pushed some bug fixes in a PR against your branch at https://github.com/nickjalbert/agentos/pull/9

**Review by andyk — APPROVED** [review]
This LGTM. Ship it!

**Comment by nickjalbert** [comment]
Merged your updates, and build is green.  Merging!  Thanks for the review. :)

**Pull request merged**
